from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from xml.sax.saxutils import escape
import json


def generate_scan_report_pdf(scan):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=colors.HexColor("#003087"), fontSize=22
    )
    verdict_colors = {
        "Safe": colors.HexColor("#00a37a"),
        "Suspicious": colors.HexColor("#c98a00"),
        "Dangerous": colors.HexColor("#c0392b"),
    }
    verdict_color = verdict_colors.get(scan.verdict, colors.black)

    verdict_style = ParagraphStyle(
        "VerdictStyle", parent=styles["Heading2"], textColor=verdict_color, fontSize=16
    )

    elements = []
    elements.append(Paragraph("PhishIQ Scan Report", title_style))
    elements.append(Spacer(1, 12))

    safe_input_data = escape(scan.input_data)
    elements.append(Paragraph(f"<b>Scan Type:</b> {scan.scan_type.capitalize()}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Scanned Input:</b> {safe_input_data}", styles["Normal"]))
    elements.append(Paragraph(f"<b>Scanned On:</b> {scan.created_at.strftime('%d %b %Y, %I:%M %p')}", styles["Normal"]))
    elements.append(Spacer(1, 16))

    elements.append(Paragraph(f"Risk Score: {scan.risk_score}/100", styles["Heading2"]))
    elements.append(Paragraph(f"Verdict: {scan.verdict}", verdict_style))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("Detection Breakdown", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    flags = json.loads(scan.flags) if scan.flags else []
    table_data = [["Points", "Reason"]]
    for reason, points in flags:
        points_display = f"+{points}" if points > 0 else "OK"
        table_data.append([points_display, escape(reason)])

    table = Table(table_data, colWidths=[0.8 * inch, 5.7 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#131926")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    elements.append(table)

    elements.append(Spacer(1, 24))
    elements.append(Paragraph(
        "Generated by PhishIQ - Phishing Detection Tool. This report is for informational purposes only.",
        styles["Italic"]
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer



